### ISSUE TITLE
update to current libraries

### ISSUE THREAD

**Issue by hipik634** [wolfmanjm/universal-panel-adapter#7]
Hi, I am trying to use uno with https://www.aliexpress.com/item/0-96-inch-oled-IIC-Serial-White-OLED-Display-Module-128X64-I2C-SSD1306-12864-LCD-Screen/32896971385.html?spm=a2g0s.9042311.0.0.27424c4dzAMkgi and after flashing hex no change on outputs. Tried compiling it and it seems, that the libraries have changed during time. also I am not sure on 128x64 . trying to connect mks sgen_L with laser ... what about led light on "communication ok" ?

**Comment by wolfmanjm** [comment]
That display is not supported. Only the older non graphics displays are supported by this. Sorry.
